#version: '3'
#services:
#  app:
#    build:
#      context: .
#      dockerfile: Dockerfile
#    container_name: foodapp
#    ports:
#      - "7654:7654"
#    environment:
#      DATASOURCE_URL: foodappdb
#      DATABASE_NAME: food-app
#      DATASOURCE_USERNAME: postgres
#      DATASOURCE_PASSWORD: 1234
#    volumes:
#      - .:/app
#    command: ["java", "-jar", "target/Food-App-0.0.1-SNAPSHOT.jar"]
#    depends_on:
#      - postgres
#
#  postgres:
#    image: postgres:alpine
#    container_name: foodappdb
#    environment:
#      POSTGRES_USER: postgres
#      POSTGRES_PASSWORD: 1234
#      POSTGRES_DB: foodapp
#    ports:
#      - "5432:5432"
#    volumes:
#      - postgres-data:/var/lib/postgresql/data
#
#volumes:
#  postgres-data: